# -*- coding: utf-8 -*-
"""QTNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1op0T543xO3NmBc9-SuC9P7II8fIVkhsO
"""

"""
BÀI TOÁN LẤY MẪU TỪ PHÂN PHỐI TỶ LỆ (LŨY THỪA)
PHƯƠNG PHÁP: Metropolis-Hastings (MCMC)
Tham khảo: Dobrow (2016), Example 5.2, trang 189

"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.special import zeta   # dùng tính hằng số chuẩn hóa


# 1. Phân phối đích (discrete power-law)

def pi_unnorm(i, s=1.5):
    """Trọng số chưa chuẩn hóa: π̃_i = i^(-s)"""
    return i ** (-s)


def exact_prob(i_max, s=1.5):
    """
    Tính xác suất chính xác bằng cách chuẩn hóa thủ công.
    C = Σ_{i=1}^{∞} i^{-s}  ≈  ζ(s)  (hàm Riemann zeta)
    """
    C = zeta(s, 1)          # ζ(s) = Σ_{k=1}^∞ k^{-s}
    probs = {i: i**(-s) / C for i in range(1, i_max + 1)}
    return probs


# 2. Thuật toán Metropolis-Hastings (rời rạc)

def mh_discrete_powerlaw(n_steps, s=1.5, seed=42):
    """
    Metropolis-Hastings lấy mẫu từ π_i ∝ i^(-s), i = 1,2,3,...

    Proposal: symmetric random walk trên Z+ với reflecting boundary tại 1
        - Tại i = 1: luôn đề xuất j = 2  (boundary)
        - Tại i > 1: đề xuất j = i-1 hoặc j = i+1, mỗi cái xác suất 1/2

    Vì proposal đối xứng (ngoại trừ tại biên), ta dùng
    Metropolis acceptance (trường hợp đặc biệt của MH):
        a(i, j) = min(1, π_j / π_i) = min(1, (i/j)^s)

    Tuy nhiên tại biên i=1, proposal KHÔNG đối xứng:
        T_{1,2} = 1  nhưng  T_{2,1} = 1/2
    Nên phải dùng Hastings correction đầy đủ:
        a(1,2) = min(1, π_2 * T_{2,1} / (π_1 * T_{1,2}))
               = min(1, 2^{-s} * (1/2) / (1^{-s} * 1))
               = min(1, (1/2)^{s+1})
               = (1/2)^{s+1}          [vì s > 0 nên tỷ số < 1]
    """
    np.random.seed(seed)
    chain    = np.zeros(n_steps, dtype=int)
    accepted = 0
    x        = 1       # bắt đầu tại i = 1

    for t in range(n_steps):
        # Đề xuất trạng thái mới
        if x == 1:
            x_prop = np.random.choice([1, 2])   # 50% self-loop, 50% đi đến 2
        else:
            x_prop = x + np.random.choice([-1, 1])  # trái hoặc phải

        # Proposal đối xứng → chỉ cần tỷ số mật độ
        log_accept = np.log(pi_unnorm(x_prop, s)) \
                     - np.log(pi_unnorm(x, s))

        # Chấp nhận / từ chối
        if np.log(np.random.uniform()) < log_accept:
            x        = x_prop
            accepted += 1

        chain[t] = x

    return chain, accepted / n_steps


# 3. Chạy mô phỏng

S        = 10 / 3          # tham số: π_i ∝ i^{-3/2}  (theo Dobrow Ex 5.2)
N_STEPS  = 1_000_000    # 1 triệu bước (như trong sách)
BURN_IN  = 50_000

print(" PHÂN PHỐI LŨY THỪA ")
print(f"  Phân phối : π_i ∝ i^(-{S}),  i = 1, 2, 3, ...")
print(f"  Proposal  : Symmetric random walk + reflecting boundary tại 1")
print(f"  Số bước   : {N_STEPS:,}  (Burn-in: {BURN_IN:,})")

chain_all, accept_rate = mh_discrete_powerlaw(N_STEPS, s=S)
chain = chain_all[BURN_IN:]

# Xác suất chính xác (tham chiếu)
exact = exact_prob(i_max=15, s=S)

print(f"\n  Tỷ lệ chấp nhận : {accept_rate:.2%}")
print(f"\n  So sánh xác suất (MCMC vs Chính xác):")
print(f"  {'i':>4}  {'MCMC':>10}  {'Chính xác':>12}  {'Sai số':>8}")
print(f"  {'-'*40}")
for i in range(1, 10):
    sim_prob   = np.mean(chain == i)
    exact_prob_i = exact[i]
    err        = abs(sim_prob - exact_prob_i) / exact_prob_i * 100
    print(f"  {i:>4}  {sim_prob:>10.4f}  {exact_prob_i:>12.4f}  {err:>7.2f}%")

tail_sim   = np.mean(chain >= 9)
tail_exact = sum(exact[i] for i in range(9, 16))
print(f"  {'≥9':>4}  {tail_sim:>10.4f}  {tail_exact:>12.4f}")


# PHẦN MỞ RỘNG (LIÊN TỤC)

def log_pareto(x, alpha=2.5, x_min=1.0):
    """Log-mật độ Pareto liên tục (không cần hằng số chuẩn hóa)."""
    if x < x_min:
        return -np.inf
    return -alpha * np.log(x)

def pareto_pdf(x, alpha=2.5, x_min=1.0):
    x = np.asarray(x, dtype=float)
    out = np.zeros_like(x)
    m = x >= x_min
    out[m] = (alpha - 1) / x_min * (x[m] / x_min) ** (-alpha)
    return out

def mh_continuous_pareto(n_steps, alpha=2.5, x_min=1.0,
                          proposal_std=0.8, seed=99):
    """
    MH với Log-Normal Random Walk Proposal cho Pareto liên tục.
    Đề xuất: x' = x * exp(ε),  ε ~ N(0, σ²)
    Có Hastings correction (Jacobian): log A += log(x') - log(x)
    """
    np.random.seed(seed)
    samples  = np.zeros(n_steps)
    accepted = 0
    x        = x_min + 0.1

    for t in range(n_steps):
        x_prop    = x * np.exp(np.random.normal(0, proposal_std))
        log_ratio = (log_pareto(x_prop, alpha, x_min)
                     - log_pareto(x, alpha, x_min)
                     + np.log(x_prop) - np.log(x))
        if np.log(np.random.uniform()) < log_ratio:
            x        = x_prop
            accepted += 1
        samples[t] = x

    return samples, accepted / n_steps

ALPHA     = 2.5
N_CONT    = 100_000
BURN_CONT = 10_000

print(f"\n PHẦN MỞ RỘNG — PARETO LIÊN TỤC (Log-Normal Proposal)")
print(f"  Phân phối : f(x) ∝ x^(-{ALPHA}),  x >= 1 (Pareto liên tục)")
print(f"  Proposal  : Log-Normal random walk, σ = 0.8")
print(f"  Số bước   : {N_CONT:,}  (Burn-in: {BURN_CONT:,})")

cont_all, cont_accept = mh_continuous_pareto(N_CONT, alpha=ALPHA)
cont_samples = cont_all[BURN_CONT:]

true_mean  = 1.0 * (ALPHA - 1) / (ALPHA - 2)
alpha_mle  = 1 + len(cont_samples) / np.sum(np.log(cont_samples))

print(f"\n  Tỷ lệ chấp nhận : {cont_accept:.2%}")
print(f"  E[X] lý thuyết  : {true_mean:.4f}")
print(f"  E[X] MCMC       : {cont_samples.mean():.4f}")
print(f"  α̂ MLE           : {alpha_mle:.4f}  "
      f"(sai số: {abs(alpha_mle-ALPHA)/ALPHA*100:.2f}%)")


# 4. VISUALIZE (cả 2 phần)

fig = plt.figure(figsize=(16, 14), facecolor='#0d1117')
fig.suptitle(
    'Lấy Mẫu từ Phân Phối Lũy Thừa bằng MCMC (Metropolis-Hastings)\n'
    'Dobrow (2016) – Example 5.2',
    fontsize=15, fontweight='bold', color='white', y=0.99
)
gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.50, wspace=0.35)

C1 = '#00d4ff'   # MCMC
C2 = '#ff6b6b'   # exact / reference
C3 = '#ffd93d'   # PDF / lý thuyết
C4 = '#7ee787'   # mean
BG = '#161b22'; GR = '#30363d'; FG = '#c9d1d9'

def sty(ax, title, xlabel='', ylabel=''):
    ax.set_facecolor(BG)
    ax.tick_params(colors=FG, labelsize=9)
    ax.set_title(title, color=FG, fontsize=10, fontweight='bold', pad=8)
    ax.grid(True, color=GR, linewidth=0.5, alpha=0.7)
    for sp in ax.spines.values(): sp.set_color(GR)
    if xlabel: ax.set_xlabel(xlabel, color=FG, fontsize=9)
    if ylabel: ax.set_ylabel(ylabel, color=FG, fontsize=9)

# ── [0,:] Trace plot (rời rạc) ──
ax0 = fig.add_subplot(gs[0, :])
show = min(3000, N_STEPS)
ax0.plot(chain_all[:show], color=C1, lw=0.5, alpha=0.85,
         label='Chuỗi Markov (rời rạc)')
ax0.axvline(BURN_IN, color=C2, lw=1.8, ls='--',
            label=f'Hết Burn-in (n={BURN_IN:,})')
ax0.set_xlim(0, show)
ax0.set_ylim(0, np.percentile(chain_all[:show], 98) + 1)
sty(ax0, f'Trace Plot — Rời rạc π_i ∝ i^(-{S})  |  {show:,} bước đầu',
    'Bước (iteration)', 'Trạng thái i')
ax0.legend(fontsize=9, facecolor='#21262d', edgecolor=GR, labelcolor=FG)

# ── [1,0] Bar chart: MCMC vs chính xác (rời rạc) ──
ax1 = fig.add_subplot(gs[1, 0])
i_vals = np.arange(1, 13)
sim_p  = np.array([np.mean(chain == i) for i in i_vals])
ext_p  = np.array([exact.get(i, 0)     for i in i_vals])
w = 0.38
ax1.bar(i_vals - w/2, sim_p, width=w, color=C1, alpha=0.8,
        label='MCMC')
ax1.bar(i_vals + w/2, ext_p, width=w, color=C2, alpha=0.8,
        label='Xác suất chính xác')
sty(ax1, f'Rời rạc: MCMC vs Chính xác  (s = {S})',
    'i', 'P(X = i)')
ax1.set_xticks(i_vals)
ax1.legend(fontsize=8, facecolor='#21262d', edgecolor=GR, labelcolor=FG)

# ── [1,1] Log-Log plot (rời rạc) ──
ax2 = fig.add_subplot(gs[1, 1])
ax2.scatter(i_vals, sim_p, s=40, color=C1, zorder=3, label='MCMC')
ax2.scatter(i_vals, ext_p, s=25, color=C2, marker='x',
            zorder=4, label='Chính xác')
ax2.set_xscale('log'); ax2.set_yscale('log')
sty(ax2, f'Log-Log: Đặc trưng Power Law (độ dốc ≈ -{S})',
    'i (log)', 'P(X=i) (log)')
ax2.legend(fontsize=8, facecolor='#21262d', edgecolor=GR, labelcolor=FG)

# ── [2,0] Histogram (liên tục) ──
ax3 = fig.add_subplot(gs[2, 0])
x_lin = np.linspace(1, 8, 400)
clip  = np.percentile(cont_samples, 98)
ax3.hist(cont_samples[cont_samples <= clip], bins=80, density=True,
         color=C1, alpha=0.65, label='MCMC (liên tục)', edgecolor='none')
ax3.plot(x_lin, pareto_pdf(x_lin, ALPHA), color=C3, lw=2.2,
         label='PDF lý thuyết')
ax3.axvline(true_mean, color=C4, lw=1.5, ls='--',
            label=f'E[X] = {true_mean:.2f}')
sty(ax3, f'Mở rộng: Pareto Liên tục (α={ALPHA}) — Histogram vs PDF',
    'x', 'Mật độ xác suất')
ax3.set_xlim(1, clip)
ax3.legend(fontsize=8, facecolor='#21262d', edgecolor=GR, labelcolor=FG)

# ── [2,1] Running mean (rời rạc — E[X] lý thuyết) ──
ax4 = fig.add_subplot(gs[2, 1])
# E[X] = Σ i * π_i / C = Σ i^{1-s} / ζ(s)
C_norm   = zeta(S, 1)
true_E   = zeta(S - 1, 1) / zeta(S, 1)  # Tỷ số ζ(7/3) / ζ(10/3)
rm = np.cumsum(chain) / np.arange(1, len(chain) + 1)
ax4.plot(rm, color=C1, lw=0.8, label='Running mean (MCMC)')
ax4.axhline(true_E, color=C4, lw=1.8, ls='--',
            label=f'E[X] lý thuyết ≈ {true_E:.3f}')
ax4.fill_between(range(len(rm)), rm, true_E, alpha=0.1, color=C1)
sty(ax4, 'Hội Tụ Running Mean — Chuỗi Rời Rạc',
    'Số mẫu (sau burn-in)', 'Trung bình tích lũy')
ax4.legend(fontsize=8, facecolor='#21262d', edgecolor=GR, labelcolor=FG)

plt.savefig('mcmc_power_law_results.png',
            dpi=150, bbox_inches='tight', facecolor='#0d1117')
print("\n  ✓ Đã lưu biểu đồ: mcmc_power_law_results.png")

# from google.colab import files
# files.download('mcmc_power_law_results.png')

plt.show()