# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8lNfQOrGjbr41N3n68L-Kz_Rn0fyqJl
"""

import numpy as np
import math as mth
import matplotlib.pyplot as plt

#Bước 1:Khởi tạo n điểm ngẫu nhiên với mẫu là 100 000 điểm
n = 100000

#Bước 2: Sinh đồng thời n giá trị xi và n giá trị yi
x = np.random.rand(n)
y = np.random.rand(n)

#Bước 3: Kiểm tra
inside = x**2 + y**2 <= 1

#Bước 4: Tính ước lượng
pi = 4* np.mean(inside)

#Nhận xét
sai_so = abs(pi - np.pi)

print(f"Ước lượng pi: {pi:.8f}")
print(f"Sai số thực nghiệm: {sai_so:.8f}")

fig, ax = plt.subplots(figsize=(6, 6))
ax.scatter(x[inside], y[inside], s=0.1, color='blue', label='Trong hình tròn')
ax.scatter(x[~inside], y[~inside], s=0.1, color='purple', label='Ngoài hình tròn')

theta = np.linspace(0, np.pi/2, 300)
ax.plot(np.cos(theta), np.sin(theta), 'b-', linewidth=2)
ax.set_aspect('equal')
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
ax.set_title(f'Monte Carlo ước lượng π ≈ {pi:.5f}')
ax.legend(markerscale=10)
plt.tight_layout()
plt.show()
