# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8lNfQOrGjbr41N3n68L-Kz_Rn0fyqJl
"""

import numpy as np
import math as mth
import matplotlib.pyplot as plt

#Bước 1:Khởi tạo n điểm ngẫu nhiên với mẫu là 100 000 điểm
n = 100000

#Bước 2: Sinh đồng thời n giá trị xi và n giá trị yi
x = np.random.rand(n)
y = np.random.rand(n)

#Bước 3: Kiểm tra
inside = x**2 + y**2 <= 1

#Bước 4: Tính ước lượng
pi = 4* np.mean(inside)

#Nhận xét
sai_so = abs(pi - np.pi)

print(f"Ước lượng pi: {pi:.8f}")
print(f"Sai số thực nghiệm: {sai_so:.8f}")